services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - api-network

  api:
    container_name: class-allocation-management-api
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    networks:
      - api-network
    depends_on:
      - db

volumes:
  db_volume:
networks:
  api-network:
    driver: bridge
